export {
  InstructorCourseSchema,
  PendingSubmissionSchema,
  InstructorDashboardStatsSchema,
  InstructorDashboardSchema,
  InstructorCourseDetailSchema,
  UpdateCourseRequestSchema,
  UpdateCourseResponseSchema,
  CourseAssignmentSchema,
  CourseAssignmentsResponseSchema,
  DeleteCourseResponseSchema,
  type InstructorCourse,
  type PendingSubmission,
  type InstructorDashboardStats,
  type InstructorDashboard,
  type InstructorCourseDetail,
  type UpdateCourseRequest,
  type UpdateCourseResponse,
  type CourseAssignment,
  type CourseAssignmentsResponse,
  type DeleteCourseResponse,
} from "../backend/schema";
