export {
  AssignmentDetailSchema,
  CourseAssignmentSummarySchema,
  SubmitAssignmentRequestSchema,
  SubmitAssignmentResponseSchema,
  AssignmentSubmissionDetailSchema,
  GradeAssignmentRequestSchema,
  GradeAssignmentResponseSchema,
  CreateAssignmentRequestSchema,
  UpdateAssignmentRequestSchema,
  AssignmentStatusSchema,
  DeleteAssignmentResponseSchema,
  type AssignmentDetail,
  type CourseAssignmentSummary,
  type SubmitAssignmentRequest,
  type SubmitAssignmentResponse,
  type AssignmentSubmissionDetail,
  type GradeAssignmentRequest,
  type GradeAssignmentResponse,
  type CreateAssignmentRequest,
  type UpdateAssignmentRequest,
  type AssignmentStatus,
  type DeleteAssignmentResponse,
} from "../backend/schema";
