export {
  AssignmentDetailSchema,
  CourseAssignmentSummarySchema,
  SubmitAssignmentRequestSchema,
  SubmitAssignmentResponseSchema,
  AssignmentSubmissionDetailSchema,
  GradeAssignmentRequestSchema,
  GradeAssignmentResponseSchema,
  type AssignmentDetail,
  type CourseAssignmentSummary,
  type SubmitAssignmentRequest,
  type SubmitAssignmentResponse,
  type AssignmentSubmissionDetail,
  type GradeAssignmentRequest,
  type GradeAssignmentResponse,
} from "../backend/schema";
